### ISSUE TITLE
Discovering this unbelievable package, FusionCharts to be implemented ?

### ISSUE THREAD

**Issue by raphaelmsr** [ArielMejiaDev/larapex-charts#19]
Thanks for this awesome project, this makes ApexCharts integration unbelievably simple
Is there a way to include FusionCharts?

**Comment by ArielMejiaDev** [comment]
Hi, there I have no plans to implement more packages as apexcharts.js is the most flexible and customizable chart library that I find, but if you has some experience working with FusionChart you can create a FusionChart Class that extends from LarapexChart class and override what you need, this is possible since Larapex v 2.x version
