### ISSUE TITLE
Publishing commands

### ISSUE THREAD

**Issue by tomsjac** [ArielMejiaDev/larapex-charts#35]
Hello,

Before starting, this package is excellent, it helps us to use the apexcharts library

However, would it be possible not to publish the command file and the stubs automatically? Because I don't need it.

Thank's you

**Comment by ArielMejiaDev** [comment]
Hi @tomsjac it can be possible, I guess it is useful because any user can edit the command and make it even more advance stubs as their project needs.

I would take this in mind if more users find that the commands and stubs are not useful in their own projects I can make the changes to make it work.

I also accept Pull Requests to change the behavior.

Thanks for the suggestion 👍 .
