### ISSUE TITLE
Stubs and Commands

### ISSUE THREAD

**Issue by MainaUrbanus** [ArielMejiaDev/larapex-charts#42]
Hello, thanks for a wonderful package. Is it possible to do away with the automatic creation of stubs and commands... I find them  not useful at the moment

**Comment by ArielMejiaDev** [comment]
Hi @MainaUrbanus of course, you can create a chart by yourself by using the `LarapexChart` facade or the `LarapexChart` class with dependency injection

just copy the code from a generated chart file and use it in your own service or controller and you only need to remove the chart command in `app/Console/Commands` and the chart stubs, and you can create the charts by yourself.

the chart file creation is helpful because the package supports a lot of methods to customize the charts and could be hard to remember all the syntax so there are proper examples, but you are free to remove the command and stubs

**Comment by MainaUrbanus** [comment]
Hello, Why did you close the issue?I am still seeing the commands and stubs being recreated even after deleting them... THis is causing me to have some permission errors and it is annoying.    On Monday, 30 August 2021, 18:55:20 GMT+3, ArielMejiaDev ***@***.***> wrote:  
 
 


Closed #42.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
