### ISSUE TITLE
is there a way we can add yaxis options?

### ISSUE THREAD

**Issue by rudysetiawan** [ArielMejiaDev/larapex-charts#52]
i would like to add something like this in the graph:
```
yaxis: {
        labels: {
           formatter: function (value) {
          return value + "$";
          }
        }
    },
```

is it possible? thank you

**Comment by ArielMejiaDev** [comment]
Yes is something that is totally posible in the apexchartsJS library, but it is something that should be added in the package, at this moment this is something that is on the plans for the next release (no due date, because it is on my free time)

Here you can check more about it: https://apexcharts.com/docs/formatting-axes-labels/

Feel free to make a PR
