### ISSUE TITLE
How do I change tooltips colours?

### ISSUE THREAD

**Issue by HakimMutalib** [ArielMejiaDev/larapex-charts#56]
![image](https://user-images.githubusercontent.com/50284961/168001572-9d559e7e-f98d-44ee-a3a6-7327d652803f.png)
![image](https://user-images.githubusercontent.com/50284961/168001594-0337b17f-44da-4c50-986d-642fe484991f.png)

**Comment by ArielMejiaDev** [comment]
Definitely is something that can be done using the based ApexchartsJS library

Check the `Styling Tooltips` section
https://apexcharts.com/docs/tooltip/

You can even create a custom tooltip
https://apexcharts.com/docs/options/tooltip/#custom

Custom tooltip example
https://codepen.io/apexcharts/pen/NBdyvV

At this moment is something that I plan to add for the next release (no due date because it requires some free time), But feel free to open a PR.
